version: '3'

services: 
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: whatsapp
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: